/**
 * The mock API every front-end test speaks to.
 *
 * Environment specific entry points are separate: `@shopping/api-mocks/node`
 * for vitest, `@shopping/api-mocks/browser` for Storybook. Both build on the
 * handlers exported here, so there is one definition of what the API answers.
 */

export { defineFixture, fixtureSchemaOf, isFixture } from './define'
export {
  apiErrorBody,
  driftedHealthPayload,
  httpFailure,
  gatedFailureOn,
  httpFailureOn,
  malformedResponse,
  MOCK_REQUEST_ID,
  mockResponseHeaders,
  networkFailure,
  networkFailureAfterOn,
  networkFailureOn,
} from './failures'
export type { GatedFailure } from './failures'
export {
  addressRowsSnapshot,
  adminClaimHandlers,
  adminClaimRowsSnapshot,
  adminSellerHandlers,
  attributeHandlers,
  CARD_LIMIT_MAX,
  CARD_LIMIT_MIN,
  cartHandlers,
  categoryHandlers,
  categoryRowsSnapshot,
  checkoutHandlers,
  claimHandlers,
  couponBoxHandlers,
  couponBoxSnapshot,
  declineNextTossApproval,
  emptyPlatformCouponStore,
  defaultHandlers,
  demoHandlers,
  failNextClaim,
  failNextDefaultAssignment,
  failNextDemoIssue,
  failNextRefresh,
  failNextSellerClaim,
  failNextPlatformCoupon,
  failNextSellerCoupon,
  failNextStockAdjustment,
  healthHandlers,
  MOCK_CARD_EXPIRES_AT,
  MOCK_CARDS_PER_USER,
  MOCK_CLAIMABLE_COUPON_CODE,
  MOCK_CLAIM_ID,
  MOCK_CLAIM_OUTCOMES,
  MOCK_CLAIM_ORDER_ID,
  MOCK_CLAIM_RETURN_WINDOW_CLOSED_AT,
  MOCK_CLAIM_RETURN_WINDOW_ENDS_AT,
  MOCK_CLAIM_SELLER_ORDER_IDS,
  MOCK_COUPON_BOX_NOW,
  MOCK_COUPON_BOX_PAGE_SIZE,
  MOCK_COUPON_SELLER_ID,
  MOCK_OTHER_SELLER_ID,
  MOCK_ADMIN_CLAIM_NOW,
  MOCK_PLATFORM_COUPON_IDS,
  MOCK_PLATFORM_COUPON_NOW,
  MOCK_ADMIN_CLAIMABLE_IDS,
  MOCK_ADMIN_CLAIMABLE_ORDER_NUMBERS,
  MOCK_ADMIN_DEFECT_RETURN_ID,
  MOCK_ADMIN_INTERVENTION_ID,
  mockCouponBoxSeedAt,
  mockCouponBoxSeeds,
  mockDemoAccount,
  MOCK_ORDER_IDS,
  MOCK_ORDER_NOW,
  MOCK_ORDER_PAGE_SIZE,
  MOCK_POINT_LEDGER_PAGE_SIZE,
  MOCK_POINT_NOW,
  MOCK_POINT_ORDER_ID,
  MOCK_SELLER_CLAIM_BRAND,
  MOCK_SELLER_CLAIM_IDS,
  MOCK_SELLER_CLAIM_NOW,
  MOCK_SELLER_CLAIM_SELLER_STEPS,
  MOCK_SELLER_CLAIM_STAGES,
  MOCK_SELLER_COUPON_NOW,
  MOCK_SELLER_ORDER_IDS,
  mockSellerCouponSeedAt,
  mockPointLedgerSeeds,
  mockSellerCouponSeeds,
  mockSession,
  orderHandlers,
  paymentHandlers,
  pointHandlers,
  platformCouponHandlers,
  platformCouponSnapshot,
  preferenceSnapshot,
  productHandlers,
  productRowsSnapshot,
  profileHandlers,
  failNextAdminClaim,
  resetAdminClaimStore,
  resetAdminSellerStore,
  resetAttributeStore,
  resetCartStore,
  resetCategoryStore,
  resetCheckoutStore,
  seedCheckoutCoupons,
  spendCouponElsewhere,
  resetClaimStore,
  resetCouponBoxStore,
  resetDemoStore,
  resetOrderStore,
  resetPaymentStore,
  resetPointStore,
  resetPlatformCouponStore,
  resetProductStore,
  resetProfileStore,
  failNextShipment,
  resetSellerClaimStore,
  resetSellerConsoleStore,
  resetSellerCouponStore,
  resetSellerOrderStore,
  resetSellerStore,
  resetSessionStore,
  resetUploadStore,
  searchHandlers,
  sellerClaimHandlers,
  sellerClaimSnapshot,
  sellerConsoleHandlers,
  sellerConsoleSnapshot,
  sellerCouponHandlers,
  sellerCouponSnapshot,
  sellerHandlers,
  sellerOrderHandlers,
  sellerOrderSnapshot,
  sellerRequests,
  sellerRowSnapshot,
  sessionHandlers,
  unresolveNextApproval,
  uploadHandlers,
  userRolesHandlers,
} from './handlers'
export type { CardTransaction, IssuedCard, SellerRequestRecord } from './handlers'
export {
  SEARCH_CATALOGUE,
  SEARCH_CATALOGUE_SELLER_ID,
  SEARCH_COAT_CATEGORY,
  SEARCH_SHOE_CATEGORY,
  searchFilters,
} from './handlers/search-catalogue'
export {
  productId as sellerProductId,
  SELLER_CATEGORY_IDS,
  SELLER_PRODUCT_COUNT,
  sellerProductListItem,
  sellerVariants,
  variantId as sellerVariantId,
} from './handlers/seller-console-catalogue'
export { mockMethods, mockPaths, MOCK_STORAGE_ORIGIN, MOCK_STORAGE_PUBLIC_ORIGIN } from './paths'
export type { MockMethod, MockPath } from './paths'
export { fixtureRegistry } from './registry'
export type { RegisteredFixture } from './registry'
export { neverAnswers, neverAnswersOn, sleepingInstance, slowResponse, wakesAfter } from './waking'
export * from './fixtures'
