-- Tables that exist only in the test databases.
--
-- Applied to the template right after `prisma migrate deploy`, so every worker
-- database is cloned with them already in place and the truncation between
-- tests — which reads `information_schema` — covers them like any other table.
--
-- They exist because TASK-0106 has to prove that the harness reproduces a real
-- race *before* the domain code that races exists: stock reservation is
-- TASK-0048, and inventing an endpoint here would be building the feature under
-- the guise of testing it. Everything below is a fixture, is never referenced by
-- `apps/api/src`, and never reaches a real database — `prisma migrate deploy`
-- alone builds the schema that ships.
--
-- Deliberately without a `CHECK ("stock" >= 0)`: the whole point of the
-- contention spec is that the conditional UPDATE keeps stock from going
-- negative. A constraint would do that job instead and the assertion would stop
-- proving anything.

CREATE TABLE "TestStock" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY,
    "variant" TEXT NOT NULL,
    "stock" INTEGER NOT NULL,

    CONSTRAINT "TestStock_pkey" PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX "TestStock_variant_key" ON "TestStock" ("variant");

CREATE TABLE "TestReservation" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY,
    "variant" TEXT NOT NULL,
    "quantity" INTEGER NOT NULL,
    -- `now()` and not an application timestamp on purpose: this column is what
    -- shows that a row written inside a transaction carries the database's clock
    -- (see the Clock port in `src/common/clock.ts`).
    "createdAt" TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT "TestReservation_pkey" PRIMARY KEY ("id")
);

CREATE INDEX "TestReservation_variant_idx" ON "TestReservation" ("variant");
