import nextPlugin from '@next/eslint-plugin-next'
import reactHooks from 'eslint-plugin-react-hooks'
import globals from 'globals'
import tseslint from 'typescript-eslint'

import { baseConfig } from './base.js'

/** Files that hold React or Next.js code in an App Router project. */
const reactFiles = ['**/*.{ts,tsx,js,jsx,mjs}']

/**
 * Next.js App Router preset. Also used by `packages/ui`, which ships React
 * components without being a Next.js app.
 *
 * The plugins are registered by hand instead of spreading the shipped presets:
 * `eslint-plugin-react-hooks` exposes its flat preset with a numerically keyed
 * `plugins` object, which would register the plugin under the wrong name.
 *
 * @param {string} rootDir Absolute path of the package being linted.
 * @returns {import('typescript-eslint').ConfigArray}
 */
export function nextConfig(rootDir) {
  return tseslint.config(
    ...baseConfig(rootDir),
    // Generated by `next dev`; not ours to lint.
    { ignores: ['next-env.d.ts', '**/.next/**'] },
    {
      files: reactFiles,
      plugins: { '@next/next': nextPlugin },
      languageOptions: {
        globals: { ...globals.browser, ...globals.node },
      },
      rules: {
        ...nextPlugin.configs.recommended.rules,
        ...nextPlugin.configs['core-web-vitals'].rules,
        // App Router only (D-009): there is no `pages/` directory for the rule to
        // scan, and it prints a warning on every run when it cannot find one.
        '@next/next/no-html-link-for-pages': 'off',
      },
    },
    {
      files: reactFiles,
      plugins: { 'react-hooks': reactHooks },
      rules: reactHooks.configs['recommended-latest'].rules,
    },
    {
      /**
       * Open Graph images are drawn by Satori, not by a browser.
       *
       * `next/image` has no meaning in an `ImageResponse`: there is no DOM, no
       * lazy loading and no LCP to protect — the whole file becomes one PNG. The
       * rule's advice is sound everywhere else and simply does not apply here.
       *
       * Scoped to Next's own reserved filenames rather than to a directory, so
       * the exemption cannot quietly grow to cover an ordinary component. The
       * token checker exempts the same names for the same kind of reason
       * (`packages/ui/test/component-tokens.spec.ts`).
       */
      files: ['**/{opengraph,twitter}-image.{ts,tsx}'],
      rules: { '@next/next/no-img-element': 'off' },
    },
  )
}
